- pipeline.id: pipeline_proveedores
  path.config: "/usr/share/logstash/pipeline/pipeline_proveedores.conf"
- pipeline.id: pipeline_proveedores_normales
  path.config: "/usr/share/logstash/pipeline/pipeline_proveedores_normlaes.conf"